### ISSUE TITLE
The system to determine when Vidi is done loading is broken

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#100]
Try to request this:
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#osm/11/39.2013/-6.8156/public.test

You will see that the "allDoneLoading:layers" event is fired before the overlays is loaded (with the console log "Vidi is now loaded"):

![image](https://user-images.githubusercontent.com/3850918/43762835-5408ba86-9a29-11e8-8762-8e18d99152ff.png)

This results in an empty legend.

The "allDoneLoading:layers" is important in the print function to determine when to create the PDF.
The process should be:

1. Baselayer and overlays are loaded async and when all are loaded the "allDoneLoading:layers" event is triggered. 
2. When the legend API is called once. In the callback window.status = "all_loaded" is set, which tells wkhtmltopdf to create the PDF.  

https://github.com/sashuk/vidi/blob/master/browser/modules/bindEvent.js#L262
https://github.com/sashuk/vidi/blob/master/browser/modules/state.js#L152'

**Comment by sashuk** [comment]
The problem was that overlays in URL were loaded with some delay after the base layer stars loading. So, there was sometimes a situation when **(1)**  `doneB` was already `true`, but, as the overlays have not started loading yet, the loadingL was `false`, so **(2)** was false-triggering the `allDoneLoading:layers` event.

Fixed in https://github.com/sashuk/vidi/commit/445cddb7ea8906cbfc4ddf9bfb6be163a7c22a3f, now base layers are starting loading at the same time (same JavaScript event loop run) with overlays

```javascript
backboneEvents.get().on("doneLoading:setBaselayer", function (e) {
    console.log("Done loading: " + e);
    doneB = true;
    loadingB = false;
    if ((doneL && doneB) || loadingL === false) {   /* (1) */
        console.log("Setting timeout to " + window.vidiTimeout + "ms");
        setTimeout(function () {
            console.info("Layers all loaded B");
            backboneEvents.get().trigger("allDoneLoading:layers");  /* (2) */
            doneB = doneL = false;
            $(".loadingIndicator").fadeOut(200);
        }, window.vidiTimeout)
    }
});
```

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/be59dbf8f63f1353d28cb121969d678f3aef3224
