### ISSUE TITLE
Dynamically created layers controls don't work any more

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#101]
Some modeles creates a layer control dynamically like the legend module:
![image](https://user-images.githubusercontent.com/3850918/43771865-c215ca48-9a40-11e8-8c0b-4ffa29bc64e5.png)
In the bindEvent.js there was this code to take care of these cases:

```javascript
$(document).arrive('[data-gc2-id]', function () {
  $(this).on("change", function (e) {
    switchLayer.init($(this).data('gc2-id'), $(this).context.checked);
    e.stopPropagation();
  });
});
```
Re-introduce this code works, but only when using the dynamically created control (un-checking in legend will turn layer off and also un-check control in layer-tree). But if you you un-check in layer-tree, the dynamically created one is nots un-checked.

**Comment by sashuk** [comment]
@mapcentia So the `legend` and `layerTree` module need to behave like in [Vidi demo application](https://kort.geofyn.dk/app/geofyn/?config=borgerkort01.json#gc2_group._b_baggrundskort01.baggrundskort01/9/10.4494/55.2388/adresser.adgangsadresser_links,_l_map_generel.tekster_samlet_wms_web)?
The code was re-introduced, both modules interact in the same way as the demo (testing with dynamic layer `test.polygon` https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#osm/12/39.2763/-6.8216/public.test_poly,test.polygon,public.test,v:public.test_line)

**Comment by sashuk** [comment]
Assuming that legend controls should react to layerTree controls and vise versa, the legend control was fixed in https://github.com/sashuk/vidi/commit/0ee1c08c808862ed84e4a06e6d81422f5eb66c9f

Tested URLs:
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.2763/-6.8216/ - without layers
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.2763/-6.8216/v:public.test_line,public.test,public.test_poly - with layers already in meta
https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#stamenTonerLite/12/39.2763/-6.8216/v:public.test_line,public.test,test.polygon,public.test_poly - with layers already in meta and one non-meta layer

**Comment by mapcentia** [comment]
@sashuk The legend was not the best example, because the legend is reloaded when layers are switch.
Try conflictSearch module here: https://dev.geofyn.dk/app/test/public/#gc2_group._b_baggrundskort01.baggrundskort01/14/10.4012/55.5076/public.theme_pdk_detailhandel_forslag_v,public.theme_pdk_lokalplan_forslag_v
Use the drawing tools to search the visible layers. Now you get some results in the lower right corner. Here you can switch layers, which contain search hits. This layer controls should correspond with the layers tree (or controls in other modules). We've more modules, that renders own layer controls. 

![image](https://user-images.githubusercontent.com/3850918/43951758-352d7c38-9c94-11e8-83bc-fac6a7936ba9.png)
The conflictSearch module is activated by

extensions: {
        browser: [
            {conflictSearch: ["index", "reportRender", "infoClick", "controller"]}
       server: [
            {conflictSearch: ["index"]}
]}

**Comment by sashuk** [comment]
@mapcentia Is conflictSearch supposed to work only with tile layers?

**Comment by sashuk** [comment]
The previous interaction mode was restored: when the change `$(document).arrive('[data-gc2-id]', () => {});` occurs, all checkboxes with specific `data-gc2-id` are checked or unchecked, so the state of checkboxes with layer visiblity controll across the entire application is the same.

All layer visibility change events are catched in `bindEvents` like it was before

https://github.com/sashuk/vidi/blob/630980eed0587e17097f13f8790bef8d77e6fdf5/browser/modules/bindEvent.js#L173-L172

However, the `conflictSearch` uses the `getVisibleLayers()` from `geocloud.js`

https://github.com/sashuk/vidi/blob/630980eed0587e17097f13f8790bef8d77e6fdf5/public/js/gc2/geocloud.js#L803

in order to fetch the list of active layers, but this function ignores vector layers, so when the `conflictSearch` builds the search results, it does not make vector layers checkboxes active, so this could be misleading fro user. I propose to make `getVisibleLayers()` return vector layers **identifiers** as well (the **identifier** in this context means the `SCHEMA.TABLE_NAME` without the layer type specifier `v:`)

**Comment by sashuk** [comment]
@mapcentia The previous interaction mode was restored: when the change `$(document).arrive('[data-gc2-id]', () => {});` occurs, all checkboxes with specific `data-gc2-id` are checked or unchecked, so the state of checkboxes with layer visiblity controll across the entire application is the same.

All layer visibility change events are catched in `bindEvents` like it was before

https://github.com/sashuk/vidi/blob/630980eed0587e17097f13f8790bef8d77e6fdf5/browser/modules/bindEvent.js#L173-L172

However, the `conflictSearch` uses the `getVisibleLayers()` from `geocloud.js`

https://github.com/sashuk/vidi/blob/630980eed0587e17097f13f8790bef8d77e6fdf5/public/js/gc2/geocloud.js#L803

in order to fetch the list of active layers, but this function ignores vector layers, so when the `conflictSearch` builds the search results, it does not make vector layers checkboxes active, so this could be misleading fro user. I propose to make `getVisibleLayers()` return vector layers **identifiers** as well (the **identifier** in this context means the `SCHEMA.TABLE_NAME` without the layer type specifier `v:`)

**Comment by mapcentia** [comment]
@sashuk I think we need a `getAllTypesOfVisibleLayers()` instead of altering `getVisibleLayers()`, because it used elsewhere.

**Comment by sashuk** [comment]
@mapcentia Thank a lot!

**Comment by sashuk** [comment]
@mapcentia The Puppeteer was integrated for PDF generation in https://github.com/sashuk/vidi/commit/a6b64b35f270151d33ca733a60db41ad791eadbe

![printing](https://user-images.githubusercontent.com/1390758/44037882-0a18a0b6-9f48-11e8-867b-892cff9c9b97.gif)

There are some minor bugs left (with image retrieval) which I will fix next

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/9f04b7b3e03c44b5d690ac13dd59fac0243ef682
