### ISSUE TITLE
Vidi on DNS vidi.gc2.io doesn't start Service Worker

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#118]
Is it about the gc2.io domain?

https://vidi.gc2.io/app/vmus/public

**Comment by sashuk** [comment]
@mapcentia Seemed like it was an issue with the `grunt production`, but the `vidi.alexshumilov.ru` installation in production works fine. The interesting thing is that the `vidi.gc2.io` reports that **Service worker registration succeeded**, but it is unable to intercept fetches. Could you please rebuild the application with `grunt production`, setting the 

https://github.com/sashuk/vidi/blob/53fee6db4099a996cfc05a6715473937b78a8d81/browser/service-worker/index.js#L3-L4

to `TRUE`? Or I could log in and do it myself, whatever will suit you best!

**Comment by mapcentia** [comment]
@sashuk Its done

**Comment by sashuk** [comment]
@mapcentia Thanks a lot! The reason is that all URLs that have `gc2.io` are bypassed by service worker (at 110 line):

https://github.com/sashuk/vidi/blob/4f4ad2635d7ab4ec1d4de8bca4837c233a35c518/browser/service-worker/index.js#L105-L111

So, could you please specify more exact URL (regexp) which should be always bypassed for `gc2.io` domain?

**Comment by mapcentia** [comment]
@sashuk
I guess this will do it:
gc2.io/api

**Comment by sashuk** [comment]
@mapcentia The cache-bypassing rule was added in https://github.com/sashuk/vidi/commit/5e7edf9ca9d27e8cda9702e0d2bc608971adfa96
