### ISSUE TITLE
Fix editor submit button, so you don't have to scroll down to find it

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#119]
![image](https://user-images.githubusercontent.com/3850918/44257649-f0ea6300-a20c-11e8-8114-a25ca61574e8.png)

**Comment by sashuk** [comment]
Implemented in https://github.com/sashuk/vidi/commit/47039e89f375af0a281a3388b29b17228d791a02

![sticky](https://user-images.githubusercontent.com/1390758/44263896-40538200-a253-11e8-889e-0339e821f57d.gif)

**Comment by mapcentia** [comment]
@sashuk Its seems that the button isn't sticky in Safari? (Both macOS and IOS)

**Comment by sashuk** [comment]
Fixed in https://github.com/sashuk/vidi/commit/cdf101eb55cd696e55634c4958e39a8e1410d4a1

![photo_2018-08-20_16-51-06](https://user-images.githubusercontent.com/1390758/44330313-476bd180-a499-11e8-987c-3a74f7801ef0.jpg)
![photo_2018-08-20_16-51-00](https://user-images.githubusercontent.com/1390758/44330315-476bd180-a499-11e8-8718-df4a705aca7a.jpg)
