### ISSUE TITLE
Table view for vector layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#132]
Each vector layer should have a button, which open the table of the layer in a modal view or dockable panel at the bottom (we need some width for tables). There is a gc2table class for this, which are use e.g. in sqlQuery: https://github.com/sashuk/vidi/blob/develop/browser/modules/sqlQuery.js#L241

**Comment by sashuk** [comment]
@mapcentia Current progress (https://github.com/sashuk/vidi/commit/cdab747fefd8ca12e98b81f6fa05038e247ad5f4, https://github.com/sashuk/vidi/commit/7b4ef740e8b13adc8bc8d7614251ac020e9f363d):

![tableview](https://user-images.githubusercontent.com/1390758/44706536-78b95280-aad4-11e8-82e9-4166a94d1ce4.gif)

Current problems that needs to be fixed:
- table data sometimes is loaded and sometimes it is not - the corresponding `store` is unstable and at some point does not have associated `layer._layers`, or the link to layer object is broken
- table has duplicated header
- the `geoJSON` property of store is only available in onLoad callback, otherwise it is unstable in same way as the `layer` property in (1)

**Comment by sashuk** [comment]
@mapcentia The initial approach of trying to implement the table view using the already drawn vector layer was initially too complicated and it required modifications of the logic of both `gc2table.js` and `layerTree` modules. Final approach operates with separate layers which is more correct and does not have any side-effects. Table view also takes into account filter settings.

Implemented in https://github.com/sashuk/vidi/commit/3a80c203f787cc0375b87855cbefe74da0536e01

![tableview](https://user-images.githubusercontent.com/1390758/44990350-54251500-afc3-11e8-8ef3-a56baba19616.gif)
