### ISSUE TITLE
Error when switching on a vector layer

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#146]
![image](https://user-images.githubusercontent.com/3850918/45346391-5e3da980-b5a9-11e8-81af-522dd250372a.png)

**Comment by sashuk** [comment]
@mapcentia The reason was that sometimes the `layerTree` was initializing before the `onEachFeature` was set by external module, so the error happened. Now the `layerTree` does not require the `onEachFeature` options upon startup.

https://github.com/sashuk/vidi/blob/7b893cf9dba1702e1ab238ff2fedd9a4f77ea0f0/browser/modules/layerTree/index.js#L590-L594
