### ISSUE TITLE
Layer tree sometimes doesn't render 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#149]
I guess this is also a #142 thing?

![image](https://user-images.githubusercontent.com/3850918/45355702-5c7fe000-b5c1-11e8-9933-f32d207b4d3a.png)

**Comment by mapcentia** [comment]
It seems to get worse when using the new sub-group

**Comment by sashuk** [comment]
@mapcentia This error was happening because of sometimes the layer meta has the `"1ull"` value, which is valid JSON, so the 

https://github.com/sashuk/vidi/commit/33d780dcb5c8975b8d9029df2abaf96186c8d1e1#diff-2cadda091253948a98d5176364cfd6dbR699

was throwin error because of using 'in' operator in String is illegal. The additional check was added in https://github.com/sashuk/vidi/commit/33d780dcb5c8975b8d9029df2abaf96186c8d1e1.
