### ISSUE TITLE
New Feature doesn't work and no attributes is shown

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#157]
First issue:
Nothing happens when clicking the New Feature plus-sign.
Second issue:
First time you edit a feature it works OK. Second time no attribute is shown
![image](https://user-images.githubusercontent.com/3850918/45618748-1cb07100-ba77-11e8-8c8e-b79765db7116.png)
![image](https://user-images.githubusercontent.com/3850918/45618750-1fab6180-ba77-11e8-8357-12e81ef4d450.png)

**Comment by sashuk** [comment]
@mapcentia Both issues fixed in https://github.com/sashuk/vidi/commit/91d03297c40e551c663bdfbe4e96bb3a969023ad and https://github.com/sashuk/vidi/commit/aab5e359b665111e149ab9dd89f5544c85a910d9

![editing](https://user-images.githubusercontent.com/1390758/45702366-3d2a1980-bba4-11e8-80e2-1a5c78501e12.gif)
