### ISSUE TITLE
Sometimes Offline Maps stop proccessing at the last tile

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#173]
![image](https://user-images.githubusercontent.com/3850918/47775680-9aab9d00-dcf0-11e8-8966-af68c2f0429b.png)

**Comment by sashuk** [comment]
@mapcentia The reason was found - the decrement of the counter was performed via `setState({ tilesLeft: this.state.tilesLeft--})` which was just not affecting the state (the decrement of left-to-load tiles has to be performed when server returns, for example, `500` error for tile request, now it on correct React-way).

Also the indication of total number of failed tiles was added (in the demo below the application was manually put into offline mode at some moments).

Implemented in https://github.com/sashuk/vidi/commit/ce8a3447ef5979130c10b0aed885999aba0e7adb

![offline](https://user-images.githubusercontent.com/1390758/47873770-04d95480-de4d-11e8-86b1-6b4e4910dd7d.gif)
