### ISSUE TITLE
Vidi (develop branch) is loading extremely slow

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#176]
https://kort.geofyn.dk/app/geofyn/?config=borgerkort01.json
Vs
https://dev.geofyn.dk/app/geofyn/?config=borgerkort01_dev.json

**Comment by sashuk** [comment]
Some metrics were taken using the Performance tab of the Chrome DevTools:

Loading the `geofyn.dk` application

| Host                    | Loading time |
| ------------------ | --------------- |
| `kort.geofyn.dk` (application build with `production` flag)   | 13s  |
| `dev.geofyn.dk` (application build without `production` flag)  | 24s  |

**Comment by mapcentia** [comment]
@sashuk If you profiles online with dev.geofyn.dk, when could you do it again? I've now checked out the latest source with the offline layer stuff:
https://dev.geofyn.dk/app/geofyn/?config=borgerkort01_dev.json
It seems to go in to some loop (bottm error)
![image](https://user-images.githubusercontent.com/3850918/48078970-baf4c380-e1ea-11e8-81af-3e10fdbdb875.png)

**Comment by sashuk** [comment]
@mapcentia The error was caused by using the hardcode geometry column, now the geometry column is taken from the layer meta (implemented in https://github.com/sashuk/vidi/commit/57dab6a36935708f178906ba143c2cf0f741bcfb). The profiling is still in process as the loading takes too long.

**Comment by mapcentia** [comment]
@sashuk the `api/meta` call is very slow on that config. The database has more that 10.000 layers, and the config uses tags as selector. Tags are kept in a JSONB fields. I'm considering as caching mechnisme which could either be implemented i Vidi or GC2. I leaning toward Vidi.
Btw the geometry field should ever be hardcoded. They can be named anything and raster tables doesn't have them.

**Comment by sashuk** [comment]
@mapcentia Could you please check if the backend is working correctly, as the request to `api/meta` seems to fail?

![error](https://user-images.githubusercontent.com/1390758/48180834-2f04a800-e360-11e8-9edf-792bd294f21e.png)

**Comment by mapcentia** [comment]
@sashuk It should be fixed now

**Comment by sashuk** [comment]
@mapcentia Thanks!

**Comment by sashuk** [comment]
@mapcentia Please checkout the latest `develop` codebase, the performance bottleneck was fixed in https://github.com/sashuk/vidi/commit/8d49af1ea5ee2e65684593811b1a089bc1a66f7b (the service worker was requested via API for every layer, so service worker was too busy answering application requests rather than requesting tiles for base layer in order to finally load the application)

![load](https://user-images.githubusercontent.com/1390758/48185548-3f248380-e370-11e8-91cb-09d49c77e0bb.gif)

**Comment by mapcentia** [comment]
@sashuk Its loading faster now, but the `connection-check.ico` takes like 5 sec. and the browser gets unresponsive.
![image](https://user-images.githubusercontent.com/3850918/48187850-8ee95780-e33c-11e8-92fd-2066895939a0.png)

**Comment by mapcentia** [comment]
@sashuk This config doesn't seem to be affected as the borgerkort01_dev.json: https://dev.geofyn.dk/app/geofyn/?config=miljoevagtfyn.json

**Comment by sashuk** [comment]
@mapcentia Please checkout the latest `develop` codebase (the `OfflineModeControlsManager.js` was working with controls that are hidden from user which took too much memory and was affecting the regular requests like in case with the `connection-check.ico`, fixed in https://github.com/sashuk/vidi/commit/e961684cf47e8f793973cdffc3eff83f2db6d5ef)

**Comment by mapcentia** [comment]
@sashuk Nice! Closing
