### ISSUE TITLE
Print template stalls loading of Vidi

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#185]
It seems that using Vidi with print template stalls the loading:

https://dev.geofyn.dk/app/test/public/?&tmpl=print.tmpl&l=inline&h=none&px=1060&py=730&td=13.%20november%202018,%208:46&d=13.%20november%202018&k=9bf85bef-56c3-4688-bdde-277938ab4630&t=&c=#gc2_group._b_baggrundskort01.baggrundskort01/13/10.4012/55.5076/

**Comment by mapcentia** [comment]
@sashuk Is it possible to write a test for the print funktionen?

**Comment by sashuk** [comment]
@mapcentia Yes, there are tests for the print template but now the build is failing, as well as these tests - I am going to fix it next. For now the fix was implemented for current issue (https://github.com/sashuk/vidi/commit/536c46732e4a4a0d84e5d7295032ee7dbb4a5fba), the reason it was failing was that server was replying with

```
{
  status: "success",
  data: {
    status: "success",
    data: {
      anchor: "...",
      bounds: "...",
      ...
    }
  }
}
```

instead of
```
{
  status: "success",
  data: {
    anchor: "...",
    bounds: "...",
    ...
  }
}
```

Now code processes both cases. Tests will be restored within the https://github.com/sashuk/vidi/issues/177 issue.
