### ISSUE TITLE
WatsonC: if create new plot before markers is shown nothing happen

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#211]
1. Start in a low zoom level like 12
2. Create a plot. Nothing happens.
3. Zoom in to level 13 and the plot appears.
4. Zoom out again and you now see the plot and can create new plots in level 12

![image](https://user-images.githubusercontent.com/3850918/49155318-f0d52580-f31a-11e8-8f92-8520b3e7bb75.png)

**Comment by sashuk** [comment]
@mapcentia The reason behind this bug was that plots were created (when zoom is less than `16`), bot not displayed because of absence of the actual plotting data. Now plots are displayed, but with corresponding message `Not all measurements in plot were loaded by this moment`. When user zoom in enough (data is actually loaded), then the plot is automatically populated. Fixed in https://github.com/sashuk/watsonc/commit/710984c706750afdfb5d598bbe3ba286c9dd68f3

![plots](https://user-images.githubusercontent.com/1390758/49160468-c5295e00-f361-11e8-806e-bdd6d1bd1d0f.gif)
