### ISSUE TITLE
Error in Edge 17/18

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#215]
With Edge 17 came support of Service Workers. But something not working when loading vector layers. They seem not to load at all. Vidi works in Edge 16, so I believe it has to do with the implementation of SW in Edge

**Comment by sashuk** [comment]
@mapcentia The fix was implemeted in https://github.com/sashuk/vidi/commit/3f79b9b0a73dbb92730fb44546ad774b837e8d1f

Turns out that Microsoft Edge 17+ supports Service Workers (the 16 version was working like in plain HTTP mode), but does not support some features of [WebAPI](https://developer.mozilla.org/en-US/docs/WebAPI), such as **FormData API** (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13596540/, https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/33929344-fully-implement-the-formdata-api), so the workaround was implemented.

![edge](https://user-images.githubusercontent.com/1390758/49568968-8866f380-f96d-11e8-89e4-ed2f6f330778.png)
