### ISSUE TITLE
ReferenceError: Unknown plugin "@babel/plugin-proposal-object-rest-spread"

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#233]
I get this error when running browserify task:
>> ReferenceError: Unknown plugin "@babel/plugin-proposal-object-rest-spread" specified in "/home/mh/Source/vidi/node_modules/react-dnd-touch-backend/.babelrc" at 0, attempted to resolve relative to "/home/mh/Source/vidi/node_modules/react-dnd-touch-backend" while parsing file: /home/mh/Source/vidi/node_modules/react-dnd-touch-backend/dist/Touch.js
Warning: Error running grunt-browserify. Use --force to continue.

If I manual install @babel/plugin-proposal-object-rest-spread it will complain about using Babel ^7.0.0

**Comment by sashuk** [comment]
@mapcentia This error was because of the new module in `watsonc`. Now, this module was removed from the Vidi `package.json` and moved to `package.json` of the `watsonc` (https://github.com/sashuk/watsonc/commit/85f8b29fda862a6df7c92c0b23af47bfa40e5a16), so whenever `watsonc` is checked out the `npm install` has to be performed in order to install all dependencies of the `watsonc` (the npm-way).

Fixed in https://github.com/sashuk/vidi/commit/1ecca783b33f2ab2ac6642ec4b3aa6d83a653288
