### ISSUE TITLE
Store Snapshot data in GC2 key/value API

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#244]
I've added a simple key/value API to GC2, where Snapshot data can be stored.

Signature:
`https://test.gc2.io/api/v2/keyvalue/[database]/[key]`

CRUD examples:
`curl -XPOST https://test.gc2.io/api/v2/keyvalue/test/mykey -d '{"test":"test"}'`
`curl -XGET https://test.gc2.io/api/v2/keyvalue/test/mykey`
`curl -XPUT https://test.gc2.io/api/v2/keyvalue/test/mykey -d '{"test":"test2"}'`
`curl -XDELETE https://test.gc2.io/api/v2/keyvalue/test/mykey`

**Comment by sashuk** [comment]
@mapcentia Great! Should the current snapshot storage mechanism be completely switched to the key-value storage (right now state snapshots are stored just in a file in Vidi app, so not working as expected)?

By the, will the key-value API someday become **protected**? It will be alright, as state snapshots need external storage only when the user is authorized, so key-value storage requests can be routed through the backend as well as with protected WMS layers requests are routed now.

**Comment by sashuk** [comment]
@mapcentia Seems like the `https://test.gc2.io/api/v2/keyvalue/[database]?[userId=123]&[browserId=123]`  route has to be added to the API service: the case when the user wants to get all the snapshots for the database (actually those that ((belong to his browser OR him personally as a GC2 user) AND belong to specific database))). The structure of stored snapshot (the `value` property of key-value storage):

```javascript
{
  "snapshot": { ... },
  "created_at": "2019-01-21T05:26:40.063Z",
  "userId": 123 || "browserId": 123
}
```

If `browserId` is set, then it can be edited only in browsers that have the special cookie set, if the `userId` is set, then only the user with the specific identifier can edit it. All snapshots are readable by everybody.

So, in order to speed up the retrieval of data, the route **GET** `https://test.gc2.io/api/v2/keyvalue/[database]?[userId=123]&[browserId=123]` should be implemented. We could fetch **all** of the snapshots for the specific database, but it could be very hard on the backend if there are thousands of heavy objects retrieved after `https://test.gc2.io/api/v2/keyvalue/[database]` that need the afterwards filtering.

**Comment by sashuk** [comment]
@mapcentia If it okay I will be glad to implement it by myself (https://github.com/mapcentia/geocloud2/commit/664596433cc8458fa529e13029c1361758a575a5)

**Comment by mapcentia** [comment]
@sashuk please go ahead and implement it in GC2 source.

**Comment by sashuk** [comment]
@mapcentia Could you please check the https://github.com/mapcentia/geocloud2/pull/55?

**Comment by sashuk** [comment]
@mapcentia The state snapshots are now stored using the key-values storage. Implemented in https://github.com/sashuk/vidi/commit/007d5ac727d1e844459c7a7508e9c69e77b96bde, https://github.com/sashuk/vidi/commit/df1594c477753e64f8d5bd4692317201ab176767 (along with tests).

:heavy_check_mark: https://travis-ci.org/sashuk/vidi/builds/484168566
