### ISSUE TITLE
Bugs in Draw module

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#245]
Bugs in Draw module: 
1. Total distance is added to line work, even if unchecked.
2. Area calculation is wrong. Is fixed in measure tool https://github.com/sashuk/vidi/issues/181

![image](https://user-images.githubusercontent.com/3850918/51166763-e825b800-18a4-11e9-94aa-8aeaa483acaa.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/76ef30b63fc2320c8fdd03bdd63fe033afb3c362 and https://github.com/sashuk/vidi/commit/bb0a20a800162b5352cea1b7906604b129382cbb

1. Total distance is not shown for polylines in the `draw` module if the corresponding option is not checked;
2. Area is calculated correctly for polygons in `draw` module.

![draw](https://user-images.githubusercontent.com/1390758/51317392-6dba8b00-1a92-11e9-8e67-07b23b31bc35.gif)
