### ISSUE TITLE
When editing existing feature the "nodes" will snap to a grid. 

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#255]
1. Click on a feature and start editing
2. Grab a "node" and drag.
The node will snap to an visible grid.
The behaviour doesn't occur when drawing a new feature

Try here:
https://map.gc2.io/app/demo_c/public/#osm/11/39.3767/-6.2225/v:public.registration

May be related: https://github.com/sashuk/vidi/issues/254

**Comment by sashuk** [comment]
@mapcentia Could you please verify if the behavior observed is invalid? Seems like vertices snap correctly (not to grid lines).

![registration](https://user-images.githubusercontent.com/1390758/51905619-a5172900-23fc-11e9-9079-ec9aab60c137.gif)

**Comment by mapcentia** [comment]
@sashuk looks alright

**Comment by sashuk** [comment]
@mapcentia Thanks! I will do more testing then and if the grid snapping will not be observed the issue will be closed.

**Comment by sashuk** [comment]
@mapcentia Am I correct that gridlines should not be used for snapping at all?

**Comment by sashuk** [comment]
@mapcentia The observed behavior was not because of wrongly enabled Grid snapping, but because of the edited feature also participated in snapping. Fixed in https://github.com/sashuk/vidi/commit/37b5ea1fee743d0b1ff76838713d3994c95a26e5 (edited features have the special flag that excludes them from snapping).
