### ISSUE TITLE
Filters on Tile layers should only be available when layer is Single Tile

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#258]
Tile filters only works when tile cache is bypassed. So the filters should not be available if  Meta property `single_tile` is not true.

**Comment by sashuk** [comment]
@mapcentia Got it, so when the `single_tile=true`, then filters are hidden and the Mapcache is requested. 

However, please consider the following case - there is a layer `test`, which has `single_tile=false` (so it is cached), but it has predefined filters set. Should the request be routed to live WMS server or to Mapcache (what has most priority - predefined filters or `single_wms` setting)?

**Comment by mapcentia** [comment]
@sashuk I think the best solution is to prioritize predefined filters. So if you set predefined filters, when the layer will use WMS

**Comment by sashuk** [comment]
@mapcentia Got it, thanks!

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/44658acace493d0b76ad53c914d903d77f43b02e

|                                                     | Mapcache is requested | Filters control is shown |
| -------------- | ----------------- | -----------------|
| Single tile and predefined filters | - |  + |
| Single tile and no predefined filters  | -  |  + |
| No single tile and predefined filters  | -  |  - |
| No single tile and no predefined filters  | +  |  - |
