### ISSUE TITLE
Editor: After initial edit of existing feature, moving it results in error

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#272]
1) Start edit an existing feature. You can move it around without problems
2) Drag a node.
3) Move the feature and one node will snap to a point far away.

**Comment by sashuk** [comment]
Details so far:
- only polygons that already exist are affected
- bug can be observed without initial moving, so just snap, move and observe

**Comment by sashuk** [comment]
State of things:

The `Leaflet.Snap` proposes to use its own editing plugin for vector features (`SnapEditing`). However, this plugin lacks the ability to drag features, so the `Leaflet.Editable` is more preferable. However, the bug, described in this issue, is probably happening because of the https://github.com/sashuk/vidi/issues/257 - after dragging the vertex of edited feature the number of vertices increases, which is probably causing the bug.

So, the plan is to dig deeper into the `Leaflet.Snap` in order to save the `Leafet + Leaflet.Draw +  Leaflet.Editable + Leafelt.Snap` integration.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/ac4f969f7885de3563132394e30615a77b7f29ef

![feature](https://user-images.githubusercontent.com/1390758/53575159-f822fe00-3bab-11e9-8f17-ad9198cb9e04.gif)
