### ISSUE TITLE
Nicer aligment of layer tools

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#276]
Right align tools:
![image](https://user-images.githubusercontent.com/3850918/54028859-bd6e2680-41a6-11e9-8daf-e001e10027cd.png)

Handle wrapping better. Sometimes the plus signs are missing. Could a small grid layout be used to handle this?

![image](https://user-images.githubusercontent.com/3850918/54028946-20f85400-41a7-11e9-96dc-d841425b0f0c.png)

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a5921f6cd1e95541ba99b8be0419bb2f7fc79423

![bigscreen](https://user-images.githubusercontent.com/1390758/54198362-41a30f80-4501-11e9-8d8c-7b69ee9d0b83.gif)

![smallscreen](https://user-images.githubusercontent.com/1390758/54198364-423ba600-4501-11e9-87f2-87444ccb2a01.gif)
