### ISSUE TITLE
Base layer in URL is matched as overlay

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#285]
If you call this URL
`https://vidi.syddjurs.dk/app/bsik/bsik/?config=bsik_test.json#bsik.positron/10/10.2647/56.3462/` with the base layer `bsik.positron` it will be switch on as overlay also:

`https://vidi.syddjurs.dk/app/bsik/bsik/?config=bsik_test.json#bsik.positron/15/10.6483/56.2292/bsik.positron`

`bsik.positron` is a layer in GC2

**Comment by sashuk** [comment]
Bug recreated https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#public.roads/9/10.4123/56.0253/

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/41aa80b9a91d35214c52a25977fc83684c4dafa9

However, now if the GC2 layer is used as a base layer in URL, it is displayed on the map, but it is not displayed as a base layer in the `Baselayers` section among all other available base layers. Should it be displayed there as well?

**Comment by mapcentia** [comment]
@sashuk No. The user should not be able to set any layer as base layer. So if the user is requesting:
`https://vidi.alexshumilov.ru/app/aleksandrshumilov/public/#public.roads/9/10.4123/56.0253/`
And `public.roads` is not a setup to be a base layer, Vidi should just take the first defined and use that.
If `public.roads` is setup to be a base layer, it should be switched on but not as overlay (the original bug issue)

**Comment by sashuk** [comment]
@mapcentia Thanks for the clarification! Additional fix in https://github.com/sashuk/vidi/commit/aced58a4b90ecb389ab2b9f90d8bd6af7d325943
