### ISSUE TITLE
Automatically apply filter on "child" layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#292]
GC2 now has a Meta property called `children`:
https://swarm.gc2.io/api/v1/meta/test4/public.routes
```json
children: [
  {
    "rel": "public.stops",
    "parent_column": "id",
    "child_column": "parent_id",
  }
]
```
This means that field `parent_id` in `public.stops` references `id` in `public.routes`. So when a filter is applied on `public.routes` the layer `public.stops` should automatically be filtered.

The two layers:
![image](https://user-images.githubusercontent.com/3850918/57032900-b49c4d00-6c4b-11e9-910c-968dd959ffeb.png)
A filter is applied on `public.routes` and `public.stops` is when filtered:
![image](https://user-images.githubusercontent.com/3850918/57032980-e1e8fb00-6c4b-11e9-945f-2c39be18760d.png)
Of course the filter on `public.routes` may yields more that one feature, so we need a `in` operator for filters like: `parent_id in (1,2)` which is supported in PostgreSQL.

There can be more than one child layer for a parent layer.

**Comment by sashuk** [comment]
@mapcentia As far as I understand the common workflow is this one:
1. Set filter for the parent;
2. Apply filter for the parent;
3. After updated parent data is fetched, generate filter conditions for children;

However, could you please specify if this should work only in case when parent layer is the vector one? As in other cases, there is no way to retrieve the parent data in order to use it in the SQL query. Or there should be separate SQL store for requesting JSON features even if the enabled layer is, for example, the tile one?

**Comment by mapcentia** [comment]
@sashuk It must work on both types of layers. But instead of using the parent ids explicit in the WHERE clause we could use a sub-query: 

`parent_id IN (SELECT id FROM routes WHERE code=11)`

So we just need to generate the WHERE clause in the sub-query from the parent filter.

`https://swarm.gc2.io/wms/test4/public?filters={"public.stops":["(parent_id IN (SELECT id FROM routes WHERE code=11))"]}&service=WMS&request=GetMap&version=1.1.1&layers=public.stops&styles=&format=image/png&transparent=true&tileSize=256&srs=EPSG:3857&width=1183&height=446&bbox=1021657.3200596661,7756982.504436256,1202507.3289823928,7825164.3336666385`

**Comment by sashuk** [comment]
@mapcentia Implemented in https://github.com/sashuk/vidi/commit/cab00a1d52da6b8d04592a65a30c064699e7cb8d.

![filters](https://user-images.githubusercontent.com/1390758/57359180-a26d6200-71a9-11e9-9455-f27a35573a73.gif)
