### ISSUE TITLE
Scroll issue on small touch screens

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#293]
It not possible to scroll down to the buttons at the bottom, here on iPhone 7:
![Billede](https://user-images.githubusercontent.com/3850918/57037865-a3a60880-6c58-11e9-8191-f853453fc0d7.GIF)

![image](https://user-images.githubusercontent.com/3850918/57037955-e7007700-6c58-11e9-9194-83155a3757a5.png)

**Comment by sashuk** [comment]
@mapcentia The issue was observed in Safari and Chrome, as well as on Android (seems like this is because of up and down bars of mobile browsers which influence the calculated height of the viewport). The issue was fixed in https://github.com/sashuk/vidi/commit/4ead8f6a803eddef225022f71a8ca05812e3af04

![demo](https://user-images.githubusercontent.com/1390758/57093168-bcd5b480-6d3f-11e9-9f9a-802635f179bc.gif)
