### ISSUE TITLE
Can't input value in filters on IOS

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#302]
The field is un-responsive on IOS:
![image](https://user-images.githubusercontent.com/3850918/57767211-1a3b0f80-7709-11e9-848b-baa5015dbefb.png)

**Comment by sashuk** [comment]
@mapcentia Could you please specify URL where it was observed? There is probably an error in the code which, when happens, crashes the entire state (and input value) update, so it looks like nothing is typed in the text field.

The described issue was tested on Chrome and Safari in the latest iOS device:

![ezgif-1-0ee31bd6e963](https://user-images.githubusercontent.com/1390758/57848594-d977ef00-780b-11e9-9662-6483240a8a89.gif)

![ezgif-1-b773157831f3](https://user-images.githubusercontent.com/1390758/57848596-d977ef00-780b-11e9-90e8-d969f2acef8b.gif)

**Comment by mapcentia** [comment]
@sashuk https://dev.geofyn.dk/app/geofyn/?config=miljoevagtfyn.json

**Comment by sashuk** [comment]
@mapcentia Thanks for the link!

After some testing following was found about the issue:
- it does not depend on the browser (tried Chrome and Safari)
- it does not depend on whenever this is production or development release (local Vidi was put into production and tested)
- it does not depend on the enabled multiple extensions (tried the same extension set locally)
- the problem is only in iOS
- seems like it depends on metadata only

**Comment by sashuk** [comment]
@mapcentia Could you please try to update the installation with the latest code? The reason it could work is that now the layer panels are not sortable, unless the sort control is touched, so it could possibly interfere with input click (touch) event.

**Comment by mapcentia** [comment]
@sashuk It works. Closing
