### ISSUE TITLE
Filters on raster layers are not base64 encoded and can result in unexpected URL decoding

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#324]
Consider a "LIKE" filter like this on a raster layer:
`filters={%22drift.vw_searchroutestop%22:[%22(linename%20ILIKE%20%27%aarhus%20Universitet/Nord%%27)%22]}`

This is URL decoded serverside and `%aa` is decoded to some character, with unexpected result. We need to base64 encode the filter on raster layers and of course base64 decode in GC2.

Because base64 can contain `+` we've to do this in browser: `encodeURIComponent(base64.encode(filter))`

And in GC2/PHP only: `base64_decode(Input::get('filters'))`

This seems to work with SQL filters for vector.

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/fa836ecd5e1e0bd06185c7a2a2f3833556272eec and https://github.com/sashuk/geocloud2/commit/87ec214880fae9b0594592a8194c1a2d39435c3c

Demo:

![filters](https://user-images.githubusercontent.com/1390758/60608195-752be180-9df1-11e9-8867-3a5e11e7e550.gif)
