### ISSUE TITLE
Can not re-order layers in sub-groups

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#327]
Tested on https://vidi.envirogissolutions.co.za/app/envirogis/?config=envirogis_c4.json
![image](https://user-images.githubusercontent.com/3850918/62598693-841f1b80-b8ea-11e9-9b1a-ae80fc75803d.png)

Also, should it not be possible to re-order the sub-groups themselves? There is no handles (the three dots)

Edit: It seems to in some sub-groups, but not the one in the image.

**Comment by sashuk** [comment]
@mapcentia There was a problem for the first-level subgroups indeed, it was fixed in https://github.com/sashuk/vidi/commit/21fde5de97416de5894d191f6ea85f48f3de30f2. The sorting or subgroups is not available (only the upper groups sorting), so this will be implemented in https://github.com/sashuk/vidi/issues/328.

Demo:
![sorting](https://user-images.githubusercontent.com/1390758/62610613-9b83f600-b936-11e9-8f46-1580c0635781.gif)


Can we please decide on test data migration (either test database can be moved manually or all data should be moved by hand) in order to control the regression?
