### ISSUE TITLE
Filter and Load strategy buttons doesn't work on default vector layers

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#329]
Layer setup:
![image](https://user-images.githubusercontent.com/3850918/62614708-3ddab400-b90c-11e9-8617-240c3ac48a0a.png)

When the two most right buttons is dead:
![image](https://user-images.githubusercontent.com/3850918/62614755-54810b00-b90c-11e9-999f-ec4d54719113.png)

It seems to work when vector is not default and you change from another type.

**Comment by mapcentia** [comment]
@sashuk Sorry, but it seems to occur when a vector layer is switched on in the URL like this:
http://127.0.0.1:3000/app/mydb/feature/#osm/11/9.92/56.732/v:feature.linestring

**Comment by sashuk** [comment]
@mapcentia Fixed in https://github.com/sashuk/vidi/commit/a98472007e02641c0c1fdeafb39fd8223859512d - the reason was the React could not plant his component into the node which was not added to DOM tree yet.

Demo:
![loading](https://user-images.githubusercontent.com/1390758/62626371-d21f3800-b959-11e9-8969-c4d7810f48f4.gif)
