### ISSUE TITLE
"Unable the determine the online status" happens a lot

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#74]
![image](https://user-images.githubusercontent.com/3850918/42633872-fd150b5e-85e1-11e8-87eb-3258bd3493d5.png)

**Comment by sashuk** [comment]
@mapcentia Could you please check if this was the plain HTTP mode? I've checked the application on machines that have never opened Vidi before, and this kind of behaviour could be only observed when the page was loaded over the HTTP.

Some warnings were added in the https://github.com/sashuk/vidi/commit/4d3036c4b49efcd28c83fd1dc5b365c730f85302 in order to make the problem resolution easier.

![warning](https://user-images.githubusercontent.com/1390758/42867231-89e4ccf4-8aa1-11e8-86eb-70f9a00ff4e6.png)

**Comment by mapcentia** [comment]
I happens also on HTTPS. Its happens after I clear the cache and unregistre the service worker.
![image](https://user-images.githubusercontent.com/3850918/43312637-32f24914-918e-11e8-995a-e288c2735260.png)

**Comment by sashuk** [comment]
@mapcentia I've successfully observed this behaviour in two cases:

- after the `Ctrl+F5` refresh (independently of the cache reset)
- when the **Bypass for network** option is checked

Could you please confirm that your case is one these?

**Comment by sashuk** [comment]
The `Ctrl+F5` problem was submitted as a [SO](https://stackoverflow.com/questions/51597231/register-service-worker-after-hard-refresh) question

**Comment by mapcentia** [comment]
@sashuk Its there any work arounds?

**Comment by sashuk** [comment]
@mapcentia Basically the `Ctrl+F5` keystrokes can be intercepted and blocked, but I think that this will mess with the user's expectations, so this is a little bit dirty trick. Additionally `Ctrl+F5` is mostly used by developers, so this will not affect the regular user experience.

**Comment by mapcentia** [comment]
@sashuk I'm closing this one
