### ISSUE TITLE
Signin in/out will duplicate layer anchor

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#8]
1) Switch on a tile layer.
/..../public/#osm/13/39.3225/-6.8991/public.test_poly

2) Sign in and you get:
/..../public/#osm/13/39.3225/-6.8991/public.test_poly,public.test_poly

**Comment by sashuk** [comment]
@mapcentia Turned out to be very interesting issue. Duplication of layer names in hash was caused by not resetting the meta data container and calling `meta.addMetaData()` with same data. So, before signing in we had, for example, **8 layers**, after sign in (after sign in the `meta.init()` is called again) the `meta.addMetaData()` is called again, so the meta is now **16 layers** - this was causing errors in layer registration and page hash.

I've checked up the **meta** module, seems like resetting meta container on every `meta.init()` will not affect anything else. Meta is reset by https://github.com/sashuk/vidi/commit/bfc587d37ebdc9592c802c6c322aaa2c9315cd05#diff-bd207e4e8f670055f5ac2b3d214a1a55R99
