### ISSUE TITLE
When switching baselayer a lot of layer-loading and loaded events are fired

### ISSUE THREAD

**Issue by mapcentia** [sashuk/vidi#81]
https://github.com/sashuk/vidi/blob/develop/browser/modules/bindEvent.js#L263
The system tracks loading layers, so when a layer is loaded it checks whether any other layers are loading. If not the "allDoneLoading:layers" event are fired.
It seems its only a issue with baselayers, so I guess it has to do with the side-by-side function?

![image](https://user-images.githubusercontent.com/3850918/43045322-e4194a0c-8db6-11e8-9aa1-bb8c3ec90c45.png)

**Comment by sashuk** [comment]
@mapcentia The problem had deep roots, that led to the actual Leaflet bug, which was fixed in the **1.3.3** version (the `load` event was firing in https://github.com/sashuk/vidi/blob/1413869adf5e1ee37e917c7cbcfe799cd3f1aa12/public/js/lib/leaflet/leaflet-src.js#L11339 as many times as many tiles were loaded), so the Leaflet was updated to the last stable version.

Another issue was that the `geocloud` is not removing the layer from the actual layer control, so whenever same layer was added in sequence, more than one cached layers were firing the `loading` and `load` events, which was causing extra logging (https://github.com/sashuk/vidi/blob/09d4ed2c2bbd0bd6a639a0ba3842807622859ae1/public/js/gc2/geocloud.js#L1567-L1576).

Fixed in https://github.com/sashuk/vidi/commit/09d4ed2c2bbd0bd6a639a0ba3842807622859ae1
